### ISSUE TITLE
More often compiled releases

### ISSUE THREAD

**Issue by DarknessStorm** [IlliumIv/ExileApi#2]
Greetings, this is not a real issue, but a wish (sorry for that)
Could you please make compiled releases more frequently?
Sure, that we can do it ourselves but...  theese newer VisualStudio versions are just insane by it's size :(

**Comment by IlliumIv** [comment]
![изображение](https://user-images.githubusercontent.com/43261017/89091225-5a93b580-d3c1-11ea-9498-190da7ee6652.png)
More?

**Comment by IlliumIv** [comment]
Changed release update algorithm.
