### ISSUE TITLE
Plugin for incubators?

### ISSUE THREAD

**Issue by rushtothesun** [IlliumIv/ExileApi#7]
Could you consider making a plugin to show a popup when a piece of equipped gear doesn't have a legion incubator on it?

**Comment by IlliumIv** [comment]
Hi.

I'll see what I can do when I find some free time.

**Comment by IlliumIv** [comment]
@rushtothesun , it's done: https://github.com/IlliumIv/BroodyHen

**Comment by rushtothesun** [comment]
> 
> 
> @rushtothesun , it's done: https://github.com/IlliumIv/BroodyHen

Thank you!
