### ISSUE TITLE
errors when compiling plugins

### ISSUE THREAD

**Issue by SilentWarrior1** [IlliumIv/ExileApi#8]
greetings.
I got some error with compiling Iconsbuilder and Healthbars plugin: (compiling with CompilePlugins.bat file)
`D:\PoeHelper\Plugins\Source\IconsBuilder-a0c38972e5bf1fe276ed1a300bada06b354c95a6\IconsBuilder.cs(216,28) : error CS7036: There is no argument given that corresponds to the required formal parameter 'modIcons' of 'MonsterIcon.MonsterIcon(Entity, GameController, IconsBuilderSettings, Dictionary<string, Size2>)'`
`D:\PoeHelper\Plugins\Source\HealthBars-76ee005373147e5c7de23b72d3b458dcc9bf9b93\HealthBars.cs(57,33) : error CS1061: 'IngameUIElements' does not contain a definition for 'SyndicatePanel' and no accessible extension method 'SyndicatePanel' accepting a first argument of type 'IngameUIElements' could be found (are you missing a using directive or an assembly reference?)
`
the same thing occured with visualstudio 2019.

**Comment by IlliumIv** [comment]
> CompilePlugins.bat 
Do not support. I'm not maintain entire ExileApi. All this repo is relict, wich single purpose to provide me comfortable tool to work with plugins.

You can download latest compiled PoeHelper with all plugins (without ExileCore.dll and GameOffsets.dll) here: https://github.com/IlliumIv/ExileApi/releases/latest

**Comment by SilentWarrior1** [comment]
can you share those two dlls needed for your compiled PoeHelper?
Or can you tell where to get them?

**Comment by IlliumIv** [comment]
Sorry i don't want share them cause TehCheat publishing it in private Discord channel.

I haven't rights to invite anybody and i don't know how to get a invite - just once i received the private message with thanks for my work about plugins and it contained a proffer to join private community. 

Which reasons do you looking for private fork? [Queuete's version](https://github.com/Queuete/ExileApi) not so bad - in contra some things work better. Also plugins maintainers trying make plugins universal - at least maintaners who work with private fork. Most of us want to plugins work independant from fork.

IconsBuilder and HealthBars already contained in Queuete's PoeHelper, u dont need to compile them trought .bat-file.
